CREATE TABLE IF NOT EXISTS sys_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64) NOT NULL,
    tenant_name VARCHAR(128) NOT NULL,
    status CHAR(1) DEFAULT '0',
    expire_time TIMESTAMP NULL,
    plan_code VARCHAR(32) DEFAULT 'FREE',
    seat_limit INT DEFAULT 10,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_tenant_code UNIQUE (tenant_code)
);

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(100) NOT NULL,
    nick_name VARCHAR(64),
    status CHAR(1) DEFAULT '0',
    role_key VARCHAR(64) DEFAULT 'TENANT_USER',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_user_tenant_username UNIQUE (tenant_id, username),
    CONSTRAINT fk_sys_user_tenant FOREIGN KEY (tenant_id) REFERENCES sys_tenant (id)
);

CREATE TABLE IF NOT EXISTS biz_demo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    amount DECIMAL(18, 2),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_biz_demo_tenant FOREIGN KEY (tenant_id) REFERENCES sys_tenant (id)
);
